#!/bin/sh
# Begin $rc_base/init.d/messagebus

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
        start)
                boot_mesg "Starting the D-Bus Messagebus Daemon..."
                loadproc /usr/bin/dbus-daemon --config-file=/etc/dbus-1/system.conf
                ;;

        stop)
                boot_mesg "Stopping the D-Bus Messagebus Daemon..."
                killproc /usr/bin/dbus-daemon
                rm /var/run/dbus/pid
                rm /var/run/dbus/system_bus_socket
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc /usr/bin/dbus-daemon
                ;;

        *)
                echo "Usage: $0 {start|stop|restart|status}"
                exit 1
                ;;
esac

# End $rc_base/init.d/messagebus
