#!/bin/sh
# Begin $rc_base/init.d/haldaemon

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting the HAL Daemon..."
		loadproc /usr/sbin/hald --use-syslog
		;;

	stop)
		boot_mesg "Stopping the HAL Daemon..."
		killproc /usr/sbin/hald
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/hald
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/haldaemon
