#!/bin/sh
########################################################################
# Begin kerberos
#
# Description : MIT Kerberos Boot Script.
#
# Authors     : Armin K. <krejzi@email.com>
#
# Version     : BLFS SVN
#
# Notes       :
#
########################################################################

### BEGIN INIT INFO
# Provides:          kerberos
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MIT Kerberos KDC and Admin Server
# Description:       Starts, stops or restarts the MIT Kerberos KDC
#                    and Admin Server
# X-LFS-Provided-By: BLFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
   start)
      log_info_msg "Starting Kerberos KDC krb5kdc"
      start_daemon /usr/sbin/krb5kdc
      log_info_msg "Starting Kerberos administrative server kadmind"
      start_daemon /usr/sbin/kadmind
      ;;

   stop)
      log_info_msg "Stopping Kerberos administrative server kadmind"
      killproc /usr/sbin/kadmind
      log_info_msg "Stopping Kerberos KDC krb5kdc"
      killproc /usr/sbin/krb5kdc
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc /usr/sbin/krb5kdc
      statusproc /usr/sbin/kadmind
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End kerberos
