#!/bin/sh
# Begin $rc_base/init.d/mysql

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

PIDFILE=/srv/mysql/`/bin/hostname`.pid
KILLDELAY=20

case "$1" in
	start)
		echo "Starting MySQL daemon..."
		failure=0
		if [ -f "$PIDFILE" ]
		then
			if /bin/ps p `cat $PIDFILE` | grep mysqld >/dev/null
			then
				print_status warning running
				exit 0
			else
				rm -f "$PIDFILE"
				if [ -f "$PIDFILE" ]
				then
					failure=1
				fi
			fi
		fi
		if [ "$failure" = "1" ]
		then
			print_status failure
		else
			/usr/bin/mysqld_safe --user=mysql 2>&1 >/dev/null &
			evaluate_retval
		fi
		;;

	stop)
		echo "Stopping MySQL daemon..."
		if [ -e "$PIDFILE" ]
		then
			killproc
		else
			print_status warning not_running
			if [ -e "$PIDFILE" ]
			then
				rm -f $PIDFILE
			fi
		fi
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/mysqld
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/mysql
