#!/bin/sh
# Begin $rc_base/init.d/nas

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
        start)
                echo "Starting the Network Audio System Server..."
                pidof nasd
                if test $? = "0"
                then
                        print_status warning running
                else
                        /usr/X11R6/bin/nasd -aa &
                        pidof /usr/X11R6/bin/nasd
                        if test $? = "0" ; then
                                print_status success
                        else
                                print_status failure
                        fi
                fi
		;;

        stop)
                echo "Stopping the Network Audio System Server..."
                killproc /usr/X11R6/bin/nasd
                ;;

        reload)
                echo "Reloading the Network Audio System Server..."
                reloadproc /usr/X11R6/bin/nasd
                ;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc /usr/X11R6/bin/nasd
                ;;

        *)
                echo "Usage: $0 {start|stop|reload|restart|status}"
                exit 1
                ;;
esac

# End $rc_base/init.d/nasd
