#!/bin/sh
########################################################################
# Begin nfs-client
#
# Description : Start statd
#
# Author      : 
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:		File locking for nfs client
# Required-Start:	network
# Should-Start:
# Required-Stop:	sendsignals
# Should-Stop:
# Default-Start:	3 4 5
# Default-Stop:		0 1 2 6
# Short-Description:	Starts statd
# Description:		Rpc.statd provides file locking on nfs.
# X-LFS-Provided-By:	LFS
### END INIT INFO

. /lib/lsb/init-functions
# Begin $rc_base/init.d/nfs-client

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

case "$1" in
	start)
		log_info_msg "Starting NFS statd..."
		start_daemon /usr/sbin/rpc.statd
		;;

	stop)
		log_info_msg "Stopping NFS statd..."
		killproc /usr/sbin/rpc.statd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/rpc.statd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/nfs-client
