#!/bin/sh
# Begin $rc_base/init.d/ntp

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting ntpd..."
		loadproc /usr/sbin/ntpd gx
		;;

	stop)
		boot_mesg "Stopping ntpd..."
		killproc /usr/sbin/ntpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/ntpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/ntp
