#!/bin/sh
# Begin /etc/init.d/postfix

### BEGIN INIT INFO
# Provides:            postfix
# Required-Start:      $syslog $local_fs $network
# Should-Start:        $remote_fs
# Required-Stop:       $network
# Should-Stop:         $remote_fs
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Postfix MTA
# Description:         Controls the Postfix Mail Transfer Agent
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

#$LastChangedBy$
#$Date$

BINFILE=/usr/lib/postfix/master
PIDFILE=/var/spool/postfix/pid/master.pid

case "$1" in
   start)
      log_info_msg "Starting Postfix..."
      start_daemon -p "${PIDFILE}" /usr/sbin/postfix start 2> /dev/null
      evaluate_retval 
      ;;

   stop)
      log_info_msg "Stopping Postfix..."
      killproc -p "${PIDFILE}" ${BINFILE}
      evaluate_retval
      ;;

   reload)
      log_info_msg "Reloading Postfix..."
      killproc -p "${PIDFILE}" ${BINFILE} -HUP
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      echo -n "postfix: "
      statusproc  -p "${PIDFILE}" ${BINFILE}
      ;;

   *)
      echo "Usage: $0 {start|stop|reload|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/postfix
