#!/bin/sh
########################################################################
# Begin /etc/init.d/svn
#
# Description : Start sshd daemon
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            $svnserve
# Required-Start:      
# Should-Start:
# Required-Stop:       $sendsignals
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts subersion server.
# Description:         Starts subversion version control system server daemon.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

#$LastChangedBy$
#$Date$

case "$1" in
	start)
		log_info_msg "Starting Subversion..."
		start_daemon /usr/bin/svnserve -d -r /srv/svn/repositories
      evaluate_retval
		;;

	stop)
		log_info_msg "Stopping Subversion..."
		killproc /usr/bin/svnserve.orig
      evaluate_retval
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/bin/svnserve.orig
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End /etc/init.d/svn
