#!/bin/sh
# Begin /etc/init.d/cyrus-sasl

### BEGIN INIT INFO
# Provides:            cyrus-sasl
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:         $remote_fs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Controls Cyrus-SASL saslauthd.
# Description:         Controls Cyrus-SASL saslauthd.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="Cyrus SASL auth daemon"
BIN_FILE="/usr/sbin/saslauthd"
PIDFILE="/var/run/saslauthd/saslauthd.pid"

case "$1" in
    start)
        start_daemon "${BIN_FILE}" -a ldap
        evaluate_retval start
    ;;

    stop)
        # slapd needs SIGINT
        killproc -p "${PIDFILE}" "${BIN_FILE}"
	evaluate_retval stop
    ;;

    restart)
        killproc -p "${PIDFILE}" "${BIN_FILE}" &&
        sleep 1 &&
        start_daemon "${BIN_FILE}"
	evaluate_retval restart
    ;;

    status)
        statusproc "${BIN_FILE}"
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;

esac

# End /etc/init.d/cyrus-sasl
