#!/bin/sh
# Begin /etc/init.d/gdm

### BEGIN INIT INFO
# Provides:            gdm
# Required-Start:      $network
# Should-Start:        cups haldaemon random $remote_fs samba sshd
# Required-Stop:       $network
# Should-Stop:         alsa cups haldaemon random $remote_fs samba sshd
# Default-Start:       5
# Default-Stop:        0 1 2 3 4 6
# Short-Description:   Starts/Stops the Gnome Display Manager (GUI Login). 
# Description:         Starts and stops the Gnome Display Manager.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

GNOME_PREFIX="/opt/gnome"
BIN_FILE="${GNOME_PREFIX}/sbin/gdm"
PIDFILE="/var/run/gdm.pid"

chk_stat

case "$1" in
    start)
        MESSAGE="Starting GDM..."
        ${GNOME_PREFIX}/sbin/gdm
        evaluate_retval generic
        ;;

    stop)
        if [ -f "$PIDFILE" ]
        then
            MESSAGE="Stopping GDM..."
            ${GNOME_PREFIX}/sbin/gdm-stop
            evaluate_retval generic
        fi
        ;;

    reload)
        MESSAGE="Reloding GDM (Safe)..."
        ${GNOME_PREFIX}/sbin/gdm-safe-restart
        evaluate_retval generic
        ;;

    restart)
        MESSAGE="Restarting GDM..."
        ${GNOME_PREFIX}/sbin/gdm-restart
        evaluate_retval generic
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

# End /etc/init.d/gdm
