#!/bin/sh
# Begin $rc_base/init.d/dhcp

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting DHCP Server..."
		loadproc /usr/sbin/dhcpd -q eth1
		;;

	stop)
		echo "Stopping DHCP Server..."
		killproc /usr/sbin/dhcpd
		;;

	reload)
		echo "Reloading DHCP Server..."
		reloadproc /usr/sbin/dhcpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/dhcpd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/dhcp
