#!/bin/sh
# Begin $network-devices/services/dhclient

# Based upon lfs-bootscripts-1.12 $network_devices/if{down,up}
# Rewritten by Nathan Coulson <nathan@linuxfromscratch.org>
# Adapted for dhclient by DJ Lucas <dj@lucasit.com>

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions
. $IFCONFIG

printstats()
{
	# Print the last 16 lines of dhclient.leases
	sed -e :a -e '$q;N;17,$D;ba' /var/state/dhcp//dhclient.leases
}

case "$2" in
        up)
                echo "Starting dhclient on the interface..."
                /sbin/dhclient $1 $DHCP_START
                # Save the return value
                RET="$?"
                # Print the assigned settings if requested
                if [ "$RET" == "0" -a "$PRINTIP" == "yes" ]; then
			# Get info from dhclient.leases file
			IPADDR=`printstats | grep "fixed-address" | \
				sed 's/ fixed-address //' | \
				sed 's/\;//'`
			NETMASK=`printstats | grep "subnet-mask" | \
				sed 's/ option subnet-mask //' | \
				sed 's/\;//'`
			GATEWAY=`printstats | grep "routers" | \
				sed 's/ option routers //' | \
				sed 's/\;//'`
			DNS=`printstats | grep "domain-name-servers" | \
				sed 's/ option domain-name-servers //' | \
				sed 's/\;//' | sed 's/,/ and /'`

                        if [ "$PRINTALL" == "yes" ]; then
                                echo ""
                                print_status success
                                echo "           DHCP Assigned Settings for $1:"
                                echo "           IP Address:      $IPADDR"
                                echo "           Subnet Mask:     $NETMASK"
                                echo "           Default Gateway: $GATEWAY"
                                echo "           DNS Server:      $DNS"
                        else
                                echo " IP Addresss:""$IPADDR"
                                print_status success
                        fi
                else
                        echo ""
                        $(exit "$RET")
                        evaluate_retval
                fi
        ;;

        down)
                echo "Stoping dhclient on the $1 interface..."
		if [ "$DHCP_STOP" == "" ]
		then
			# This breaks multiple interfaces please provide
			# the correct stop arguments.
			killproc dhclient
		else
                	/sbin/dhclient $1 $DHCP_STOP
                	evaluate_retval
		fi
        ;;

        *)
                echo "Usage: $0 [interface] {up|down}"
                exit 1
        ;;
esac

# End $network_devices/services/dhclient
