#!/bin/sh
# Begin $rc_base/init.d/cups

#$LastChangedBy$
#$Date$

# Start or stop the CUPS server based upon the first argument to the script.

. /etc/sysconfig/rc
. $rc_functions

case $1 in
	start)
		echo "Starting CUPS Printserver..."
		loadproc /usr/sbin/cupsd
		;;

	stop)
		echo "Stopping CUPS Printserver..."
		killproc /usr/sbin/cupsd
		;;

	reload)
		echo "Reloading CUPS Printserver..."
		reloadproc /usr/sbin/cupsd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/cupsd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/cups
