#!/bin/sh
########################################################################
# Begin lisa
#
# Description : 
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            lisa
# Required-Start:      network
# Should-Start:
# Required-Stop:       sendsignals
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts lisa daemon.
# Description:         Starts Trinity lisa daemon.
# X-LFS-Provided-By:   LFS
### END INIT INFO

TRINITY_PREFIX=/opt/trinity
. /lib/lsb/init-functions

#$LastChangedBy$
#$Date$

export PATH=$PATH:$TRINITY_PREFIX/bin

case "$1" in
   start)
      log_info_msg "Starting LISA Daemon..."
      start_daemon $TRINITY_PREFIX/bin/lisa
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping LISA Daemon..."
      killproc $TRINITY_PREFIX/bin/lisa
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc $TRINITY_PREFIX/bin/lisa
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/lisa
