#!/bin/sh
# Begin $rc_base/init.d/nfs-client

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting NFS statd..."
		loadproc /usr/sbin/rpc.statd

		echo "Starting NFS lockd..."
		loadproc /usr/sbin/rpc.lockd
		;;

	stop)
		echo "Stopping NFS lockd..."
		killproc /usr/sbin/rpc.lockd

		echo "Stopping NFS statd..."
		killproc /usr/sbin/rpc.statd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/rpc.statd
		statusproc /usr/sbin/rpc.lockd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/nfs-client
