#!/bin/sh
# Begin $rc_base/init.d/sshd

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "Starting SSH Server..."
		loadproc /usr/sbin/sshd
		;;

	stop)
		boot_mesg "Stopping SSH Server..."
		killproc /usr/sbin/sshd
		;;

	reload)
		boot_mesg "Reloading SSH Server..."
		reloadproc /usr/sbin/sshd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/sshd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/sshd
