#!/bin/bash
# Begin $rc_base/init.d/winbind

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy$
#$Date$

. /etc/sysconfig/rc
. $rc_functions

PIDFILE="/var/run/winbindd.pid"
KILLDELAY="10"

case "$1" in

        start)
                echo "Starting winbind..."
                loadproc winbindd
                ;;

        stop)
                echo "Stopping winbind..."
		killproc winbindd

	reload)
		echo "Reloading winbind..."
		reloadproc winbindd
		;;

        restart)
                $0 stop
                sleep 1
                $0 start
                ;;

        status)
                statusproc winbindd
                ;;

        *)
                echo "Usage: $0 {start|stop|reload|restart|status}"
                exit 1
                ;;

esac

# End $rc_base/init.d/winbind
