#!/bin/sh
# Begin $network-devices/services/dhcpcd
                                                                                
# Based upon lfs-bootscripts-1.12 $network_devices/if{down,up}
# Rewritten by Nathan Coulson <nathan@linuxfromscratch.org>
# Adapted for dhcpcd by DJ Lucas <dj@lucasit.com>

. /etc/sysconfig/rc
. $rc_functions
. $IFCONFIG

PIDFILE="/var/run/dhcpcd-$1.pid"
LEASEINFO="/var/lib/dhcpc/dhcpcd.$1.info"

case "$2" in
        up)
                echo "Bringing up the $1 interface (dhcpcd)..."
                # Test to see if there is a stale pid file
                if [ -f "$PIDFILE" ]
                then
                    ps `cat "$PIDFILE"` | grep dhcpcd > /dev/null
                    if [ $? != 0 ]
                    then
                        rm -f /var/run/dhcpcd-$1.pid > /dev/null
                    else
                        print_status warning running
                        exit 2
                    fi
                fi
                /sbin/dhcpcd $1 $DHCP_START
                evaluate_retval
        ;;
                                                                                
        down)
		# Do nothing if we have an infinate lease time as
		# the client exits when started in this case.
		if [ -e "$LEASEINFO" ]
		then
		    . $LEASEINFO
		else
		    # Have to print something here to let the user know
		    # that there is something wrong with their setup
		    echo "Bringing down the $1 interface..."
		    print_status warning not_running
		    exit 1
		fi

		if [ "$LEASETIME" == "4294967295" ]
		then
		    # Do nothing and exit
		    exit 0
		fi

                echo "Bringing down the $1 interface (dhcpcd)..."
		if [ "$DHCP_STOP" == "" ]
		then
		    # 2nd argument is not used when PIDFILE is set,
		    # but killproc requires a second argument
		    # currently in LFS bugzilla
		    killproc dhcpcd
		else
                    /sbin/dhcpcd $1 $DHCP_STOP
                    evaluate_retval
                fi
        ;;
                                                                                
        *)
                echo "Usage: $0 [interface] {up|down}"
                exit 1
        ;;
esac
                                                                                
# End $network_devices/services/dhcpcd
